name: Build and Test Node.js Application
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: 
  workflow_dispatch:  
jobs:
  verify-install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: verify installation
        run: npm ci
        
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'      
      - run : npm audit || true
  test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the code
          uses: actions/checkout@v5
        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '16' 
        - name: Testing app
          run: npm test
          continue-on-error: true         
         
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the code
          uses: actions/checkout@v5
        - name: Build docker image
          run: |
            docker build -t nodejs-simple-app --file Dockerfile .
      needs: [test, audit]    